# Generated by Django 5.2.6 on 2025-09-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.URLField(default='https://cdn-icons-png.flaticon.com/512/1147/1147856.png')),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('is_veg', models.BooleanField(default=True)),
            ],
        ),
    ]
